# -*- coding: utf-8 -*-
"""função.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qIa-k2cyaDKX4hSlu8dBCHtV95FISEJ
"""



import matplotlib.pyplot as plt
import numpy as np

def plot_first_degree_function():
    print("--- PLOTADOR DE FUNÇÃO DE PRIMEIRO GRAU (y = ax + b) ---")

    try:
        a = float(input("Digite o valor de 'a' (coeficiente angular): "))
        b = float(input("Digite o valor de 'b' (coeficiente linear): "))
    except ValueError:
        print("Entrada inválida! Por favor, digite números para 'a' e 'b'.")
        return

    # Gera pontos para o eixo x
    x = np.linspace(-10, 10, 400)  # Gera 400 pontos entre -10 e 10

    # Calcula os valores correspondentes de y
    y = a * x + b

    # Cria o gráfico
    plt.figure(figsize=(8, 6))
    plt.plot(x, y, label=f'y = {a}x + {b}', color='blue')

    # Adiciona detalhes ao gráfico
    plt.title('Gráfico da Função de Primeiro Grau')
    plt.xlabel('Eixo X')
    plt.ylabel('Eixo Y')
    plt.grid(True)
    plt.axhline(0, color='black', linewidth=0.5) # Eixo X
    plt.axvline(0, color='black', linewidth=0.5) # Eixo Y
    plt.legend()
    plt.show()

# Chama a função para executar
plot_first_degree_function()